### ISSUE TITLE
SceneManager location

### ISSUE THREAD

**Issue by nguyenlamlll** [vilbeyli/VQEngine#122]
Hi @vilbeyli, 

I'm looking through the engine and there is one thing that is bugging me which is the location of SceneManager class definition/implementation although they are used in several places. I tried to search for the files or for the texts but it's literally nowhere to be found within this repository. Am I missing something here?

Thank you.

**Comment by nguyenlamlll** [comment]
Um, just realized. Is it a part of your re-design for scenes? 😄

**Comment by vilbeyli** [comment]
Hi @nguyenlamlll 

The scene system is pretty immature and not very flexible at this moment. The design is as follows:

[Scene.h](https://github.com/vilbeyli/VQEngine/blob/master/Source/Engine/Scene.h) has the responsiblity of a SceneManager - it handles scene resource management. It is also the base class for all the scene instances (VQEngine has 5 scenes at the moment)

The derived scene objects are using the 'Scene Interface for Derived Classes' functions of the Scene.h for material/game object/texture creation. Scenes are also somewhat data driven and currently require scene files (.scn), which can be found in Data/Scenes. You can launch the engine, load a scene, make changes to the file and reload the scene on the fly.

Adding a new scene is quite involved at the moment, which is not the best design, but here are the requirements in case you want to know :
 - Create a new .scn file next to the others
 - Add .cpp/.h files for the new scene to the Scenes project under VQEngine solution. You can use the script in the Scenes folder: `.\NEW_SCENE.bat myAwesomeNewScene`
      - This will create the header and cpp files from the template so that you can directly jump into building your scene
- Include the new scene header in the Engine.h, and follow the other scenes from there. I've left comments explaining how to add the necessary changes to actually load your scene.

The scene parser is also quite immature. I wanted to learn what goes into writing a Scene I/O system and hence I ended up with the design above. My focus is on rendering capabilities at the moment so I'll probably switch to some third party library for parsing such as XML or JSON sometime in the future.

Let me know if you have further questions:)

**Comment by nguyenlamlll** [comment]
Hi @vilbeyli, 

Thank you so much for the details. I understand them better now. For the time being, I think we can close this issue. 😄 

And yes, if we can parse scene information from JSON files (maybe use RapidJSON?) at runtime, that would be awesome. But how about Lua? Is it possible or a better choice?

**Comment by vilbeyli** [comment]
@nguyenlamlll There are currently no plans in the near future for the scripting system. I might try to offload the Scene code into a .dll and enable on-the-fly-cpp-editing by re-compiling and loading the dll while the engine runs but the priority for this task is not very high at this moment.
