### ISSUE TITLE
Quaternion implementation

### ISSUE THREAD

**Issue by SonicZentropy** [vilbeyli/VQEngine#123]
This is a clarification question more than an issue -- I'm using VQEngine as a (fantastic) reference along with Luna to learn DirectX.  I'm just curious why your Transforms use a custom implementation for Quaternions instead of using the XMQuaternion implementation from DXMath?  Thanks for the great reference implementations, btw!

**Comment by vilbeyli** [comment]
@SonicZentropy Hi there.

I just wanted to understand how Quaternions work so I implemented them on my own and used XMQuaternion to unit test the results of my implementation. No other reason :)

**Comment by SonicZentropy** [comment]
Excellent!  I'm glad I didn't miss anything afterall.  Thanks so much!
