### ISSUE TITLE
Internal compiler error

### ISSUE THREAD

**Issue by NewSkyLineTwitter** [vilbeyli/VQEngine#163]
When I go into VS and try to build it, it gives me an internal Compiler error in the `Texture.cpp` file. When I click on the the error it jumps to line 356:
```cpp
const UINT cellHeight = TextureWidth >> 3;    // The height of a cell in the checkerboard texture.
```

Any idea how to fix it? Help would be appreciated. :)

**Comment by vilbeyli** [comment]
I've reported this bug to Microsoft some weeks ago: https://developercommunity.visualstudio.com/t/post/10113090

Use `/ 8` instead of `>> 3` and it should be good.
